#version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    container_name: cinemaabyss-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: cinemaabyss
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cinemaabyss-network

  # ZooKeeper for Kafka
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: cinemaabyss-zookeeper
    ports:
      - "2181:2181"
    networks:
      - cinemaabyss-network
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

 # Kafka
  kafka:
    image: 'bitnami/kafka:3.1'
#    platform: linux/amd64
    restart: always
    container_name: cinemaabyss-kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: yes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cinemaabyss-network

  # Monolith Service
  monolith:
    build:
      context: ./src/monolith
      dockerfile: Dockerfile
    container_name: cinemaabyss-monolith
    restart: on-failure:3
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_CONNECTION_STRING: postgres://postgres:postgres_password@postgres:5432/cinemaabyss?sslmode=disable
    networks:
      - cinemaabyss-network

  # Movies Microservice
  movies-service:
    build:
      context: src/microservices/movies-service
      dockerfile: Dockerfile
    container_name: cinemaabyss-movies-service
    restart: on-failure:3
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    environment:
      PORT: 8081
      DB_CONNECTION_STRING: postgres://postgres:postgres_password@postgres:5432/cinemaabyss?sslmode=disable
    networks:
      - cinemaabyss-network

  # Events Microservice
  events-service:
    build:
      context: src/microservices/events-service
      dockerfile: Dockerfile
    container_name: cinemaabyss-events-service
    restart: on-failure:3
    depends_on:
      - postgres
      - kafka
    ports:
      - "8082:8082"
    environment:
      PORT: 8082
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC_USER: user-events
      KAFKA_TOPIC_PAYMENT: payment-events
      KAFKA_TOPIC_MOVIE: movie-events
      KAFKA_CONSUMER_GROUP_ID: events-service-group
    networks:
      - cinemaabyss-network

  # Proxy Service (API Gateway)
  proxy-service:
    build:
      context: src/microservices/proxy-service
      dockerfile: Dockerfile
    container_name: cinemaabyss-proxy-service
    restart: on-failure:3
    depends_on:
      - monolith
      - movies-service
      - events-service
    ports:
      - ${PROXY_PORTS}
    environment:
      PORT: ${PROXY_PORT}
      MONOLITH_URL: ${MONOLITH_URL}
      MOVIES_SERVICE_URL: ${MOVIES_SERVICE_URL}
      EVENTS_SERVICE_URL: ${EVENTS_SERVICE_URL}
      GRADUAL_MIGRATION: ${GRADUAL_MIGRATION}
      MOVIES_MIGRATION_PERCENT: ${MOVIES_MIGRATION_PERCENT}
    networks:
      - cinemaabyss-network

  # Kafka UI for monitoring Kafka
  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    container_name: cinemaabyss-kafka-ui
    depends_on:
      - kafka
    platform: linux/amd64
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: event_kafka_ui
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - cinemaabyss-network

volumes:
  postgres-data:

networks:
  cinemaabyss-network:
    name: cinemaabyss-network
    driver: bridge