apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: YVd4a1lYSXRhVHBuYUhCZloycEVZblJoVkZwUGVWWkdjWEZrYjI1WGVrdDBZekZxTXpOWVFXbHVNV1kxV1hsaw==
type: kubernetes.io/dockerconfigjson
