server:
  address: ":8080"
  gradualMigration: "true"

monolith:
  baseURL: "http://monolith:8080"
  timeoutSeconds: 30

cinemaMetadata:
  baseURL: "http://movies-service:8081"
  timeoutSeconds: 10

features:
  moviesFeatureFlag: 0.5  # 50% трафика на новый сервис

